### ISSUE TITLE
ItemStack.displayName to .name for standardization

### ISSUE THREAD

**Issue by Sombian** [OneLiteFeatherNET/Microtus#41]
both `Lore` and `Name` are under `ItemStack`'s `display` tag.
yet `Lore` can be modified with method `.lore` whereas `Name` is `.displayName`, which is odd.

**Comment by theEvilReaper** [comment]
I do agree that renaming would make sense for the consistency. However, I don't like changing `displayname` to `name`. This would cause breaking changes for all extensions that rely on the standard Minestom version or its forks. In my opinion it would be more reasonable to update the corresponding tag variable.

**Comment by Sombian** [comment]
@theEvilReaper how about keep & deprecate the existing method(`.displayName`) and add `.name`?

**Comment by theEvilReaper** [comment]
@Sombian while retaining the old methods and cross-referencing them with the new ones is acceptable, it's important to note that we must continue supporting the old methods for an extended duration to ensure compatibility with the original minestom version and forks. The deprecation of the .displayName method could potentially confuse users who are new to the server software. Users coming from platforms like Paper are accustomed to using .setDisplayName to set the name for an ItemStack.

**Comment by Sombian** [comment]
@theEvilReaper minestom has already moved away from using the term `World`, opting instead for `Instance`. Honestly this change initially confused me, until i've come to realize that minestom's fundamental architecture is quite distinct. while acknowledging the contributions of past users from platforms like spigot and paper certainly has its bright sides, this juncture presents an opportune moment to rectify any inconsistencies before the project gains further momentum.

**Comment by Sombian** [comment]
@TheMeinerLP lovely...

**Comment by theEvilReaper** [comment]
Hey, sorry for the brief pause in the discussion. I've been thinking about this topic again over the past few days. I understand the intention behind it in terms of consistency, but I'm not entirely convinced about adding new methods for it. On one hand, .name is not as descriptive as .displayname. Additionally, the ItemStack has been implemented as a facade. With a facade, changes are usually made to the implementation rather than the facade itself. The facade is only modified if there's no other option. In this specific example, renaming the tag variable is the better approach
